### ISSUE TITLE
Error when using it on Linux (Ubuntu)

### ISSUE THREAD

**Issue by anik786** [Shopify/shopify_theme#130]
I tried using this app in Linux and it is not working. I got the following error:

```
Are you sure you want to completely replace your shop theme assets? This is not undoable.
Continue? (Y/N):  Y
/usr/lib/ruby/gems/1.9.1/gems/shopify_theme-0.0.21/lib/shopify_theme.rb:57:in `asset_list': undefined method `collect' for nil:NilClass (NoMethodError)
	from /usr/lib/ruby/gems/1.9.1/gems/shopify_theme-0.0.21/lib/shopify_theme/cli.rb:115:in `replace'
	from /usr/lib/ruby/gems/1.9.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /usr/lib/ruby/gems/1.9.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/lib/ruby/gems/1.9.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /usr/lib/ruby/gems/1.9.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /usr/lib/ruby/gems/1.9.1/gems/shopify_theme-0.0.21/bin/theme:24:in `<top (required)>'
	from /usr/bin/theme:23:in `load'
	from /usr/bin/theme:23:in `<main>'
```

Is this because the app is not supported on Linux or something else?

**Comment by csaunders** [comment]
The gem should just work on linux. What version of ruby are you running (`ruby -v`)? I know it works on at least 1.9.3, could you perhaps be on an older version?

**Comment by anik786** [comment]
1.9.3p484

**Comment by csaunders** [comment]
I'm not sure what could be going on here. Perhaps your credentials are invalid?

The [go version I'm maintaining](https://github.com/csaunders/phoenix/releases) let's you connect to a proxy like mitmproxy to help with debugging. Perhaps give that one a try instead?

**Comment by csaunders** [comment]
This is a late update, but your configuration was probably incorrect.

The error messages definitely need to be improved, instead of barfing out random Ruby stack traces.

Make sure your `config.yml` file is in the same directory as where you are running the command. Also be sure your configuration is setup correctly. We have information about this on the [readme](https://github.com/Shopify/shopify_theme#setting-up-shopify-theme)
